development:
  adapter: postgresql
  encoding: utf8
  database: train
  pool: 5
  username: train   
  password: secret

production:
  adapter: postgresql
  encoding: utf8
  database: Office_production
  pool: 5
  username: deploy
  password: secret
